service: codeberry-heart-counter
frameworkVersion: '3'
plugins:
  - 'serverless-esbuild'
  - serverless-offline

package:
  individually: true

custom:
  stage: ${opt:stage, env:STAGE, 'development'}
  serverless-offline:
    httpPort: 3333
    lambdaPort: 2333
    noPrependStageInUrl: true
  esbuild:
    tsconfig: 'tsconfig.app.json'

params:
  prod:
    production: true
  default:
    production: false

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${self:custom.stage}
  endpointType: REGIONAL
  timeout: 20
  environment:
    APP_ENV: ${self:custom.stage}
    IS_PRODUCTION: ${param:production}
    NODE_OPTIONS: --enable-source-maps

functions:
  - ${file(./src/handlers/codeberryHeartCounter/sls.yml):functions}
