service: codeberry-heart-counter
frameworkVersion: '4'
plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true

package:
  individually: true

custom:
  stage: ${opt:stage, env:STAGE, 'development'}
  serverless-offline:
    httpPort: 3333
    lambdaPort: 2333
    noPrependStageInUrl: true

params:
  prod:
    production: true
  default:
    production: false

provider:
  name: aws
  profile: laszlobekessy-terraform
  runtime: nodejs22.x
  stage: ${self:custom.stage}
  endpointType: REGIONAL
  timeout: 20
  environment:
    APP_ENV: ${self:custom.stage}
    IS_PRODUCTION: ${param:production}
    NODE_OPTIONS: --enable-source-maps
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:us-east-1:390834751709:table/CodeberryHeartCounter*

functions:
  - ${file(./src/handlers/codeberryHeartCounter/sls.yml):functions}
