name: 'codeberryschool.com / PRODUCTION deployment'

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'apps/codeberryschool-com/**'
      - '.github/workflows/codeberryschool-com**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_WEBSITE_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_WEBSITE_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_DEPLOY_WEBSITE_REGION }}

      - name: Deploy artifacts to S3
        working-directory: apps/codeberryschool-com/src
        run: aws s3 sync ./ s3://codeberryschool.com/ --delete

      - name: Invalidate CloudFront cache (Error tolerant)
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_WEBSITE_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_WEBSITE_KEY_SECRET }}
          AWS_REGION: ${{ secrets.AWS_DEPLOY_WEBSITE_REGION }}
          DISTRIBUTION: ${{ secrets.AWS_CODEBERRYSCHOOL_COM_CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/*'
        continue-on-error: true
